//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the build system.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: AssemblyTitle("Lumen")]
[assembly: AssemblyDescription("An application framework.")]
[assembly: AssemblyProduct("Lumen")]
[assembly: AssemblyCopyright("Copyright (c) Mattias Rydengren 2013")]
[assembly: AssemblyVersion("0.2.7")]
[assembly: AssemblyInformationalVersion("0.2.7")]
[assembly: AssemblyFileVersion("0.2.7")]
[assembly: AssemblyDelaySign(false)]
